version: '3'
services:
  fp-api:
    build: .
    environment:
      DB_HOST: mongodb
    ports:
      - 3000:80
    volumes:
      - facultyprofilesfiles:/fp-files
    links:
      - mongodb
    depends_on:
      - mongodb
  mongo-seed:
    build: ./mongo-seed
    restart: on-failure
    volumes:
      - facultyprofilesfiles:/fp-files
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    volumes:
      - facultyprofilesdb:/data/db
volumes:
  facultyprofilesdb: {}
  facultyprofilesfiles: {}
